
server:
  port: 8700

dynamodb:
  local: true

springdoc:
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: aws

dynamodb:
  local: false
